-- It might be prefereable to use the uuid as the PRIMARY KEY

CREATE TABLE wedo_projects (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    last_accessed TIMESTAMP DEFAULT now() NOT NULL,
    uuid TEXT NOT NULL
);