CREATE TABLE wedo_categories (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    title TEXT NOT NULL,
    index INTEGER,
    project_id INTEGER
        REFERENCES wedo_projects(id) ON DELETE CASCADE NOT NULL
);