CREATE TABLE wedo_categories (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    uuid TEXT NOT NULL UNIQUE, -- in case of collision the new category will simply not be created
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    title TEXT NOT NULL,
    color TEXT,
    index INTEGER,
    project_id INTEGER
        REFERENCES wedo_projects(id) ON DELETE CASCADE NOT NULL
);