CREATE TABLE wedo_tasks (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    uuid TEXT NOT NULL UNIQUE, --in case of collision the new task will simply not be created
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    title TEXT NOT NULL,
    index INTEGER,
    tags TEXT,
    notes TEXT,
    category_uuid TEXT
        REFERENCES wedo_categories(uuid) ON DELETE CASCADE NOT NULL
);