CREATE TABLE wedo_tasks (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    date_created TIMESTAMP DEFAULT now() NOT NULL,
    title TEXT NOT NULL,
    index INTEGER,
    tags TEXT,
    notes TEXT,
    category_id INTEGER
        REFERENCES wedo_categories(id) ON DELETE CASCADE NOT NULL
);